import type {
  SystemSettings,
  Member,
  MonthlyDeposit,
  LumpsumDeposit,
  LandInvestment,
  LandSaleOffer,
  PublicLandSubmission,
  MemberLandProposal,
  Director,
  GalleryItem,
  DashboardStats,
  AppNotification,
} from '../types';

export const initialSystemSettings: SystemSettings = {
  id: 'bob-settings-main',
  project_title: 'বন্ধন ও বিনিয়োগ (BONDHON O BINIYOG)',
  slogan_bengali: 'যৌথ স্বপ্ন • নিশ্চিত ভবিষ্যৎ',
  logo_url: '/bob-logo.png',
  notice_bengali: 'জরুরি নোটিশ: ২০২৬ অর্থ-বছরের জন্য পূর্বাচল সেক্টর ২১ সংলগ্ন ১০ কাঠা জমির অবশিষ্ট ১২টি শেয়ার বরাদ্দ কার্যক্রম চলছে। মাসিক কিস্তির অর্থ প্রতি মাসের ১০ তারিখের মধ্যে জমা দেওয়ার জন্য অনুরোধ করা যাচ্ছে।',
  banner_ad_active: true,
  banner_ad_badge: 'বিশেষ অফার ও বোনাস লট',
  banner_ad_text: 'ঈদ স্পেশাল অফার: পূর্বাচল প্রজেক্টে এই মাসে নতুন শেয়ার বুকিং করলেই পাচ্ছেন সাব-কবলা রেজিস্ট্রেশনে বিশেষ ছাড় ও অগ্রাধিকারমূলক লট বণ্টন!',
  banner_ad_image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop&q=80',
  banner_ad_validity: '৩০ অক্টোবর ২০২৬ পর্যন্ত প্রযোজ্য',
  banner_ad_action_text: 'এখনই অফারটি গ্রহণ করুন',
  hero_title: 'যৌথ বিনিয়োগে ভূমির মালিকানা, নিশ্চিত ভবিষ্যৎ ও সমৃদ্ধ আগামী',
  hero_subtitle: 'বন্ধন ও বিনিয়োগ (BoB) হলো একটি বিশ্বস্ত সমবায় ভূমি বিনিয়োগ উদ্যোগ। ক্ষুদ্র ক্ষুদ্র মাসিক সঞ্চয় ও সদস্যদের এককালীন যৌথ বিনিয়োগে আমরা লাভজনক ও ঝামেলামুক্ত ভূমি প্রকল্পের মালিকানা নিশ্চিত করি।',
  target_amount: 10000000, // ১ কোটি টাকা
  project_vision: 'বন্ধন ও বিনিয়োগ (BoB) হলো একটি বিশ্বস্ত সমবায় ভূমি বিনিয়োগ উদ্যোগ। ক্ষুদ্র ক্ষুদ্র মাসিক সঞ্চয় ও সদস্যদের এককালীন যৌথ বিনিয়োগে আমরা লাভজনক ও ঝামেলামুক্ত ভূমি প্রকল্পের মালিকানা নিশ্চিত করি। সম্পূর্ণ স্বচ্ছ হিসাবনিকাশ, সরকারি দলিল সম্পাদন এবং সমবন্টনই আমাদের মূল অঙ্গীকার।',
  contact_phone_1: '+880 1712-345678',
  contact_phone_2: '+880 1890-123456',
  contact_whatsapp: '+880 1712-345678',
  contact_email: 'bondhon.biniyog@gmail.com',
  contact_address: 'বাড়ি নং ১২, রোড নং ৫, ব্লক-ডি, বসুন্ধরা আ/এ, ঢাকা-১২২৯',
  call_cta_phone: '+880 1712-345678',
  call_cta_text: 'সরাসরি কল করুন (অফিস ও হটলাইন)',
  call_cta_timing: 'সকাল ৯:০০ টা থেকে রাত ১০:০০ টা (সপ্তাহের ৭ দিন)',
  management_lead: 'সজিব মোল্লা',
  management_lead_designation: 'ব্যবস্থাপনা পরিচালক ও প্রধান সমন্বয়ক',
  management_lead_phone: '+880 1712-345678',
  footer_text: '© 2026 বন্ধন ও বিনিয়োগ (BONDHON O BINIYOG)। সর্বস্বত্ব সংরক্ষিত। ব্যবস্থাপনায়— সজিব মোল্লা।',
  voucher_signature_url: 'https://api.dicebear.com/7.x/initials/svg?seed=Sajib+Molla&backgroundColor=transparent&textColor=1e3a8a',
  voucher_signatory_name: 'সজিব মোল্লা',
  voucher_signatory_title: 'ব্যবস্থাপনা পরিচালক ও প্রধান সমন্বয়ক',
  voucher_seal_text: 'বন্ধন ও বিনিয়োগ অনুমোদিত ডিজিটাল সিল',
  payment_bank_name: 'BRAC Bank PLC (ব্র্যাক ব্যাংক পিএলসি)',
  payment_bank_account_name: 'BONDHON O BINIYOG (বন্ধন ও বিনিয়োগ)',
  payment_bank_account_no: '1501-2049-88001',
  payment_bank_branch: 'বসুন্ধরা / গুলশান শাখা, ঢাকা',
  payment_bank_routing: '060261789',
  payment_bkash_no: '01712-345678 (মার্চেন্ট পেমেন্ট)',
  payment_nagad_no: '01890-123456 (ব্যক্তিগত / ক্যাশ-ইন)',
  payment_rocket_no: '01712-345678-0 (মার্চেন্ট)',
  payment_instructions: 'বিকাশ/নগদ/রকেটে Payment অথবা ব্যাংক অ্যাকাউন্টে জমা করার পর প্রাপ্ত Transaction ID (TrxID) এবং ডিপোজিট স্লিপের ছবি/স্ক্রিনশট আপলোড করে ভাউচার দাখিল করুন। অ্যাডমিন অনুমোদনের সাথে সাথে আপনার অ্যাকাউন্টে টাকা জমা হবে ও ডিজিটাল রসিদ ইস্যু হবে।',
};

export const initialMembers: Member[] = [
  {
    member_id: 'BoB-001',
    full_name: 'সজিব মোল্লা (অ্যাডমিন)',
    email: 'admin@bob.com',
    phone: '+880 1712-345678',
    password_hash: 'admin123',
    role: 'Admin',
    status: 'Active',
    monthly_target: 10000,
    total_monthly_paid: 120000,
    total_lumpsum_paid: 300000,
    grand_total_paid: 420000,
    due_installments: 0,
    owned_shares: 5,
    has_accepted_terms: true,
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    joined_date: '2025-01-01',
  },
  {
    member_id: 'BoB-002',
    full_name: 'মোহাম্মদ তানভীর আহমেদ',
    email: 'tanvir@bob.com',
    phone: '+880 1819-987654',
    password_hash: 'member123',
    role: 'Member',
    status: 'Active',
    monthly_target: 5000,
    total_monthly_paid: 60000,
    total_lumpsum_paid: 200000,
    grand_total_paid: 260000,
    due_installments: 0,
    owned_shares: 3,
    has_accepted_terms: true,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    joined_date: '2025-02-15',
  },
  {
    member_id: 'BoB-003',
    full_name: 'নুসরাত জাহান',
    email: 'nusrat@bob.com',
    phone: '+880 1911-223344',
    password_hash: 'member123',
    role: 'Member',
    status: 'Active',
    monthly_target: 5000,
    total_monthly_paid: 45000,
    total_lumpsum_paid: 100000,
    grand_total_paid: 145000,
    due_installments: 1,
    owned_shares: 2,
    has_accepted_terms: true,
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    joined_date: '2025-03-10',
  },
  {
    member_id: 'BoB-004',
    full_name: 'মোঃ কামরুল হাসান',
    email: 'kamrul@bob.com',
    phone: '+880 1622-556677',
    password_hash: 'member123',
    role: 'Member',
    status: 'Active',
    monthly_target: 5000,
    total_monthly_paid: 30000,
    total_lumpsum_paid: 100000,
    grand_total_paid: 130000,
    due_installments: 0,
    owned_shares: 1,
    has_accepted_terms: true,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    joined_date: '2025-04-05',
  },
  {
    member_id: 'BoB-005',
    full_name: 'আব্দুর রহিম (নতুন আবেদন)',
    email: 'rahim@bob.com',
    phone: '+880 1533-889900',
    password_hash: 'member123',
    role: 'Member',
    status: 'Pending',
    monthly_target: 5000,
    total_monthly_paid: 0,
    total_lumpsum_paid: 0,
    grand_total_paid: 0,
    due_installments: 0,
    owned_shares: 0,
    has_accepted_terms: false,
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    joined_date: '2026-09-20',
  },
];

export const initialMonthlyDeposits: MonthlyDeposit[] = [
  {
    deposit_id: 'MD-202609-01',
    member_id: 'BoB-001',
    member_name: 'সজিব মোল্লা (অ্যাডমিন)',
    month_year: '2026-09',
    amount: 10000,
    payment_method: 'Bank',
    trx_id: 'EBL-TRX-9988221',
    voucher_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    status: 'Approved',
    submitted_at: '2026-09-02 11:30',
    approved_by: 'System Admin',
    approved_at: '2026-09-02 12:00',
    admin_note: 'Verified with Bank Statement',
  },
  {
    deposit_id: 'MD-202609-02',
    member_id: 'BoB-002',
    member_name: 'মোহাম্মদ তানভীর আহমেদ',
    month_year: '2026-09',
    amount: 5000,
    payment_method: 'bKash',
    trx_id: 'BK9A772X51',
    voucher_url: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    status: 'Approved',
    submitted_at: '2026-09-05 14:15',
    approved_by: 'System Admin',
    approved_at: '2026-09-05 15:00',
    admin_note: 'bKash Merchant Verified',
  },
  {
    deposit_id: 'MD-202609-03',
    member_id: 'BoB-003',
    member_name: 'নুসরাত জাহান',
    month_year: '2026-09',
    amount: 5000,
    payment_method: 'Nagad',
    trx_id: 'NGD8841029',
    voucher_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    status: 'Pending',
    submitted_at: '2026-09-24 16:45',
  },
  {
    deposit_id: 'MD-202609-04',
    member_id: 'BoB-004',
    member_name: 'মোঃ কামরুল হাসান',
    month_year: '2026-09',
    amount: 5000,
    payment_method: 'bKash',
    trx_id: 'BK3M991A80',
    voucher_url: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    status: 'Pending',
    submitted_at: '2026-09-24 18:20',
  },
];

export const initialLumpsumDeposits: LumpsumDeposit[] = [
  {
    lumpsum_id: 'LS-2026-001',
    member_id: 'BoB-001',
    member_name: 'সজিব মোল্লা (অ্যাডমিন)',
    purpose: 'পূর্বাচল গ্রিন সিটি ভিউ প্রজেক্ট - ৩টি শেয়ার ক্রয় বাবদ',
    amount: 300000,
    target_land_id: 'LAND-01',
    target_land_name: 'পূর্বাচল গ্রিন সিটি ভিউ প্রজেক্ট',
    payment_method: 'Bank',
    trx_id: 'BRAC-TRX-443311',
    voucher_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    status: 'Approved',
    submitted_at: '2026-05-10 10:00',
    approved_by: 'System Admin',
    approved_at: '2026-05-10 11:30',
    admin_note: 'Approved. Shares certificate issued #CERT-01',
  },
  {
    lumpsum_id: 'LS-2026-002',
    member_id: 'BoB-002',
    member_name: 'মোহাম্মদ তানভীর আহমেদ',
    purpose: 'পদ্মা সেতু হাইওয়ে অ্যাগ্রো ল্যান্ড - ২টি শেয়ার বাবদ',
    amount: 200000,
    target_land_id: 'LAND-02',
    target_land_name: 'পদ্মা সেতু হাইওয়ে অ্যাগ্রো ও রিসোর্ট ল্যান্ড',
    payment_method: 'Bank',
    trx_id: 'CITY-TRX-776655',
    voucher_url: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    status: 'Approved',
    submitted_at: '2026-06-15 15:30',
    approved_by: 'System Admin',
    approved_at: '2026-06-15 16:00',
    admin_note: 'Approved. Shares certificate issued #CERT-02',
  },
  {
    lumpsum_id: 'LS-2026-003',
    member_id: 'BoB-003',
    member_name: 'নুসরাত জাহান',
    purpose: 'পূর্বাচল প্রজেক্ট - ১টি অতিরিক্ত শেয়ার বুকিং',
    amount: 100000,
    target_land_id: 'LAND-01',
    target_land_name: 'পূর্বাচল গ্রিন সিটি ভিউ প্রজেক্ট',
    payment_method: 'Bank',
    trx_id: 'DBBL-TRX-102938',
    voucher_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    status: 'Pending',
    submitted_at: '2026-09-24 19:10',
  },
];

export const initialLandInvestments: LandInvestment[] = [
  {
    land_id: 'LAND-01',
    land_name: 'পূর্বাচল গ্রিন সিটি ভিউ প্রজেক্ট',
    location: 'পূর্বাচল সেক্টর ২১ সংলগ্ন, ৩০০ ফিট এক্সপ্রেসওয়ে, ঢাকা',
    area_size: '১০ কাঠা (প্রাইম কমার্শিয়াল ও রেসিডেন্সিয়াল প্লট)',
    purchase_price: 5000000,
    current_valuation: 6500000,
    total_shares: 50,
    share_price: 100000,
    sold_shares: 38,
    monthly_installment: 5000,
    status: 'Active',
    sale_status: 'Available_For_Sale',
    public_asking_price: 6800000,
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'রাজউকের পূর্বাচল নতুন শহরের প্রাণকেন্দ্রে অবস্থিত এই জমিটি দ্রুত বর্ধনশীল এবং শতভাগ নিষ্কণ্টক। ৩০০ ফিট এক্সপ্রেসওয়ে থেকে মাত্র ৫ মিনিটের দূরত্ব। ভবিষ্যতে বহুতল বাণিজ্যিক বা বিলাসবহুল আবাসন প্রকল্পের জন্য অত্যন্ত উপযোগী।',
    features: ['১০০% নিষ্কণ্টক সিএস/আরএস/সিটি জরিপ সম্পন্ন', '৪০ ফুট প্রশস্ত প্রধান পাকা রাস্তা সংলগ্ন', 'বিদ্যুৎ, গ্যাস ও সাব-স্টেশন সংযোগ জোন', 'উচ্চ ভবিষ্যৎ মূলধন বৃদ্ধি সম্ভাবনা (বার্ষিক ১৮-২২%)'],
    shares_detail: [
      { share_id: 'S-01', land_id: 'LAND-01', member_id: 'BoB-001', member_name: 'সজিব মোল্লা', share_count: 5, certificate_no: 'CERT-P01-001', assigned_date: '2025-05-12' },
      { share_id: 'S-02', land_id: 'LAND-01', member_id: 'BoB-002', member_name: 'মোহাম্মদ তানভীর আহমেদ', share_count: 3, certificate_no: 'CERT-P01-002', assigned_date: '2025-06-15' },
      { share_id: 'S-03', land_id: 'LAND-01', member_id: 'BoB-003', member_name: 'নুসরাত জাহান', share_count: 2, certificate_no: 'CERT-P01-003', assigned_date: '2025-07-20' },
      { share_id: 'S-04', land_id: 'LAND-01', member_id: 'BoB-004', member_name: 'মোঃ কামরুল হাসান', share_count: 1, certificate_no: 'CERT-P01-004', assigned_date: '2025-08-10' },
    ],
  },
  {
    land_id: 'LAND-02',
    land_name: 'পদ্মা সেতু হাইওয়ে অ্যাগ্রো ও রিসোর্ট ল্যান্ড',
    location: 'মাওয়া এক্সপ্রেসওয়ে টোলপ্লাজা সংলগ্ন, মুন্সীগঞ্জ',
    area_size: '৩ বিঘা (৬০ কাঠা উন্মুক্ত সমতল ভূমি)',
    purchase_price: 7500000,
    current_valuation: 9200000,
    total_shares: 75,
    share_price: 100000,
    sold_shares: 42,
    monthly_installment: 5000,
    status: 'Active',
    sale_status: 'Available_For_Sale',
    public_asking_price: 9500000,
    images: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'ঢাকা-মাওয়া এক্সপ্রেসওয়ের অত্যন্ত কাছে অবস্থিত এই প্রাকৃতিক মনোরম জমিটি ইকো-রিসোর্ট, এগ্রো ট্যুরিজম ও দীর্ঘমেয়াদী ল্যান্ড ব্যাংকিং এর জন্য উপযুক্ত। পদ্মা সেতু চালুর পর এই অঞ্চলের ভূমির দাম দ্রুত গতিতে বৃদ্ধি পাচ্ছে।',
    features: ['পদ্মা এক্সপ্রেসওয়ে সংযোগ সড়ক', 'বন্যা ও জলাবদ্ধতা মুক্ত উঁচু উর্বর জমি', 'ইকো-রিসোর্ট বা এগ্রিকালচারাল ফার্মিং উপযোগী', 'বাৎসরিক প্রত্যাশিত মূলধনী মুনাফা ২০% পর্যন্ত'],
    shares_detail: [
      { share_id: 'S-05', land_id: 'LAND-02', member_id: 'BoB-001', member_name: 'সজিব মোল্লা', share_count: 4, certificate_no: 'CERT-M02-001', assigned_date: '2025-08-01' },
      { share_id: 'S-06', land_id: 'LAND-02', member_id: 'BoB-002', member_name: 'মোহাম্মদ তানভীর আহমেদ', share_count: 2, certificate_no: 'CERT-M02-002', assigned_date: '2025-09-01' },
    ],
  },
  {
    land_id: 'LAND-03',
    land_name: 'সাভার হেমায়েতপুর লজিস্টিক হাব প্লট',
    location: 'হেমায়েতপুর বাসস্ট্যান্ড সংলগ্ন, সাভার, ঢাকা',
    area_size: '১৫ কাঠা (বাণিজ্যিক ও ওয়্যারহাউজ স্পট)',
    purchase_price: 6000000,
    current_valuation: 7800000,
    total_shares: 60,
    share_price: 100000,
    sold_shares: 25,
    monthly_installment: 7500,
    status: 'In Discussion',
    sale_status: 'Under_Offer',
    public_asking_price: 8000000,
    images: [
      'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80',
    ],
    description: 'ঢাকার প্রবেশদ্বারে সাভারের ব্যস্ত বাণিজ্যিক এলাকায় গোডাউন ও ওয়্যারহাউজ তৈরির জন্য নির্ধারিত প্রকল্প। বায়না চুক্তি সম্পন্ন হয়েছে, রেজিস্ট্রি প্রক্রিয়াধীন।',
    features: ['ভারী যানবাহন ও ট্রেলার চলাচলের প্রশস্ত প্রবেশপথ', 'শিল্প ও বাণিজ্যিক বিদ্যুতের সরাসরি সুবিধা', 'মাসিক নিয়মিত ভাড়া আয়ের সর্বোচ্চ সম্ভাবনা'],
    shares_detail: [],
  },
];

export const initialLandSaleOffers: LandSaleOffer[] = [
  {
    offer_id: 'BUY-OFFER-101',
    land_id: 'LAND-01',
    land_name: 'পূর্বাচল গ্রিন সিটি ভিউ প্রজেক্ট',
    buyer_name: 'ইঞ্জিনিয়ার মোস্তাফিজুর রহমান',
    address: 'বাড়ি ১২, রোড ৫, ধানমন্ডি, ঢাকা',
    mobile: '+880 1711-223344',
    proposed_price: 6600000,
    notes: 'পুরো প্লট এককালীন বায়না দলিলের মাধ্যমে কিনতে আগ্রহী। সরেজমিন পরিদর্শনের সময় নির্ধারণ করতে অনুরোধ করছি।',
    status: 'Pending',
    submitted_at: '2026-09-24 15:20',
  },
  {
    offer_id: 'BUY-OFFER-102',
    land_id: 'LAND-02',
    land_name: 'পদ্মা সেতু হাইওয়ে অ্যাগ্রো ও রিসোর্ট ল্যান্ড',
    buyer_name: 'হাসান চৌধুরী (গ্রিন রিসোর্টস লিমিটেড)',
    address: 'গুলশান ২, ঢাকা',
    mobile: '+880 1819-556677',
    proposed_price: 9300000,
    notes: 'রিসোর্ট প্রকল্পের জন্য জমিটি খুবই উপযোগী মনে হয়েছে। মালিকানা সংক্রান্ত কাগজপত্রের কপি দরকার।',
    status: 'Contacted',
    submitted_at: '2026-09-22 18:40',
  },
];

export const initialPublicLandSubmissions: PublicLandSubmission[] = [
  {
    submission_id: 'SELL-SUB-201',
    seller_name: 'হাজী রফিকুল ইসলাম',
    address: 'কেরানীগঞ্জ, ঢাকা',
    mobile: '+880 1912-334455',
    land_size: '৭ কাঠা উঁচু ভিটামাটি',
    location: 'কেরানীগঞ্জ রোহিতপুর বাজার সংলগ্ন পাকা রাস্তা',
    expected_price: 4500000,
    photos: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    ],
    status: 'Pending',
    submitted_at: '2026-09-24 12:15',
    admin_notes: 'দলিলপত্র সিএস/আরএস খতিয়ান যাচাই করা প্রয়োজন।',
  },
  {
    submission_id: 'SELL-SUB-202',
    seller_name: 'আনিসুর রহমান',
    address: 'গাজীপুর সদর, গাজীপুর',
    mobile: '+880 1611-889900',
    land_size: '১.৫ বিঘা সমতল কৃষি ও বাণিজ্যিক উপযোগী জমি',
    location: 'ঢাকা-ময়মনসিংহ মহাসড়কের ১ কিমি ভেতরে',
    expected_price: 6000000,
    photos: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
    ],
    status: 'Under Review',
    submitted_at: '2026-09-20 10:30',
    admin_notes: 'সাইট ভিজিট সম্পন্ন হয়েছে। জমির অবস্থান ভালো।',
  },
];

export const initialMemberLandProposals: MemberLandProposal[] = [
  {
    proposal_id: 'MEM-PROP-301',
    member_id: 'BoB-002',
    member_name: 'মোহাম্মদ তানভীর আহমেদ',
    location: 'মুন্সীগঞ্জ সিরাজদিখান হাইওয়ে সংলগ্ন',
    land_size: '২ বিঘা',
    estimated_price: 4000000,
    description: 'আমার এলাকার সংলগ্ন এই জমিটি সমবায় উদ্যোগে ক্রয় করে প্লটিং বা ইকোফার্মিং করলে সদস্যরা অত্যন্ত লাভবান হবেন। বিক্রেতা অবিলম্বে বায়না করতে প্রস্তুত।',
    photos: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    ],
    status: 'Pending',
    submitted_at: '2026-09-23 14:00',
  },
];

export const initialDirectors: Director[] = [
  {
    director_id: 'DIR-01',
    name: 'সজিব মোল্লা',
    designation: 'ব্যবস্থাপনা পরিচালক ও প্রধান সমন্বয়ক',
    phone: '+880 1712-345678',
    email: 'sajib.molla@bob.com',
    photo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    message: 'আমাদের লক্ষ্য প্রতিটি মধ্যবিত্ত ও পেশাজীবীর জন্য নির্ভেজাল ভূমিতে যৌথ মালিকানার একটি নিরাপদ, স্বচ্ছ ও লাভজনক প্ল্যাটফর্ম তৈরি করা। সততা ও অঙ্গীকারই বন্ধন ও বিনিয়োগের ভিত্তি।',
    order: 1,
  },
  {
    director_id: 'DIR-02',
    name: 'মোহাম্মদ ইকবাল হোসেন',
    designation: 'পরিচালক (প্রকল্প ও ভূমি ব্যবস্থাপনা)',
    phone: '+880 1819-123456',
    email: 'iqbal.hossain@bob.com',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    message: 'জমি নির্বাচন থেকে শুরু করে কাগজপত্র যাচাই, নামজারি ও সীমানা নির্ধারণ— প্রতিটি ধাপে আমরা শতভাগ সতর্কতা ও আইনগত সঠিকতা নিশ্চিত করি।',
    order: 2,
  },
  {
    director_id: 'DIR-03',
    name: 'অ্যাডভোকেট তানভীর আহমেদ',
    designation: 'পরিচালক (আইন ও নিবন্ধন বিষয়ক)',
    phone: '+880 1911-987654',
    email: 'adv.tanvir@bob.com',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    message: 'প্রতিটি সদস্যের বিনিয়োগের নিরাপত্তা বিধানে সুনির্দিষ্ট স্ট্যাম্প চুক্তি, সাব-কবলা দলিল ও শেয়ার সনদের মাধ্যমে বৈধ আইনি কাঠামো প্রয়োগ করা হয়।',
    order: 3,
  },
  {
    director_id: 'DIR-04',
    name: 'ফারহানা আকতার',
    designation: 'পরিচালক (অর্থ ও অডিট কমিটি)',
    phone: '+880 1622-334455',
    email: 'farhana.audit@bob.com',
    photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    message: 'প্রতিটি টাকা ব্যাংকিং চ্যানেলে জমা হয়। মাসিক আর্থিক বিবরণী সদস্যদের ড্যাশবোর্ডে উন্মুক্ত রাখা আমাদের জিরো-টরারেন্স স্বচ্ছতার প্রমাণ।',
    order: 4,
  },
];

export const initialGalleryItems: GalleryItem[] = [
  {
    id: 'GAL-01',
    title: 'পূর্বাচল প্রজেক্টের সাইট পরিদর্শন ও সীমানা পিলার স্থাপন',
    category: 'ভূমি জরিপ ও সাইট ভিজিট',
    image_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
    date: '২০২৬ সালের জানুয়ারি',
    location: 'পূর্বাচল সেক্টর ২১, ঢাকা',
  },
  {
    id: 'GAL-02',
    title: 'মৌজা ম্যাপ ও দলিলপত্র যৌথ যাচাইকরণ সভা',
    category: 'আইনি নিরীক্ষা',
    image_url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    date: '২০২৬ সালের ফেব্রুয়ারি',
    location: 'BoB প্রধান কার্যালয়, ঢাকা',
  },
  {
    id: 'GAL-03',
    title: 'পদ্মা হাইওয়ে এগ্রো ল্যান্ডের বার্ষিক সদস্য মিলনমেলা',
    category: 'সদস্য সম্মেলন',
    image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop&q=80',
    date: '২০২৬ সালের মে',
    location: 'মাওয়া হাইওয়ে রিসোর্ট প্রাঙ্গণ',
  },
  {
    id: 'GAL-04',
    title: 'সাব-রেজিস্ট্রি অফিসে যৌথ বায়না দলিল সম্পাদন',
    category: 'দলিল সম্পাদন',
    image_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
    date: '২০২৬ সালের জুলাই',
    location: 'রূপগঞ্জ সাব-রেজিস্ট্রি অফিস',
  },
  {
    id: 'GAL-05',
    title: 'ডিজিটাল নকশা প্রণয়ন ও আধুনিক প্ল্যানিং পর্যালোচনা',
    category: 'প্রকৌশল ও নকশা',
    image_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80',
    date: '২০২৬ সালের আগস্ট',
    location: 'BoB কনফারেন্স রুম',
  },
  {
    id: 'GAL-06',
    title: 'নতুন ভূমি প্রকল্পের মাটি পরীক্ষা ও ড্রেজিং সার্ভে',
    category: 'ভূমি জরিপ',
    image_url: 'https://images.unsplash.com/photo-1498084393753-b411b2d26b34?w=800&auto=format&fit=crop&q=80',
    date: '২০২৬ সালের সেপ্টেম্বর',
    location: 'হেমায়েতপুর, সাভার',
  },
];

export const initialAppNotifications: AppNotification[] = [
  {
    id: 'NOTIF-01',
    target_member_id: 'BoB-003',
    target_role: 'Member',
    type: 'due_installment',
    title: '⚠️ বকেয়া কিস্তি পরিশোধ নোটিশ',
    message: 'সম্মানিত নুসরাত জাহান, আপনার ১টি মাসিক কিস্তি বকেয়া রয়েছে (মোট বকেয়া ৳৫,০০০)। অনুগ্রহ করে প্রতি মাসের ১০ তারিখের মধ্যে বকেয়া পরিশোধ নিশ্চিত করুন।',
    created_at: '2026-09-24 10:00',
    read_by: [],
    link_tab: 'dashboard',
  },
  {
    id: 'NOTIF-02',
    target_member_id: 'ALL',
    target_role: 'ALL',
    type: 'land_offer',
    title: '🏡 নতুন জমি ক্রয়ের প্রস্তাব এসেছে!',
    message: 'পূর্বাচল গ্রিন সিটি ভিউ প্রজেক্ট-এ ইঞ্জিনিয়ার মোস্তাফিজুর রহমান ৳৬৬,০০,০০০-এর ক্রয়ের প্রস্তাব দাখিল করেছেন। বিস্তারিত বিবেচনাধীন।',
    created_at: '2026-09-24 15:20',
    read_by: [],
    link_tab: 'marketplace',
  },
  {
    id: 'NOTIF-03',
    target_member_id: 'ALL',
    target_role: 'ALL',
    type: 'land_submission',
    title: '🗺️ সমবায়ের জন্য নতুন জমি বিক্রির প্রস্তাব দাখিল!',
    message: 'কেরানীগঞ্জ রোহিতপুর বাজার সংলগ্ন পাকা রাস্তা সংলগ্ন ৭ কাঠা উঁচু জমি বিক্রির প্রস্তাব জমা হয়েছে (প্রত্যাশিত মূল্য: ৳৪৫ লাখ)।',
    created_at: '2026-09-24 12:15',
    read_by: [],
    link_tab: 'marketplace',
  },
  {
    id: 'NOTIF-04',
    target_member_id: 'ALL',
    target_role: 'ALL',
    type: 'member_proposal',
    title: '🤝 নতুন প্রকল্প সমবায় প্রস্তাবনা!',
    message: 'সদস্য মোহাম্মদ তানভীর আহমেদ "মুন্সীগঞ্জ সিরাজদিখান হাইওয়ে সংলগ্ন" ২ বিঘা নতুন সমবায় জমি ক্রয়ের প্রস্তাব দাখিল করেছেন।',
    created_at: '2026-09-23 14:00',
    read_by: [],
    link_tab: 'marketplace',
  },
];

export const initialStats: DashboardStats = {
  total_capital: 1075000,
  total_monthly_capital: 255000,
  total_lumpsum_capital: 820000,
  target_amount: 10000000,
  capital_percentage: 11,
  total_members: 5,
  active_members: 4,
  pending_members: 1,
  blocked_members: 0,
  pending_monthly_deposits: 2,
  pending_lumpsum_deposits: 1,
  total_pending_deposits_count: 3,
  total_pending_amount: 110000,
  active_lands_count: 2,
  total_land_shares: 185,
  sold_land_shares: 105,
  total_sale_offers: 2,
  pending_sale_offers: 1,
  total_public_submissions: 2,
  pending_public_submissions: 1,
  total_member_proposals: 1,
  pending_member_proposals: 1,
};
